spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: postgres
    password: admin
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090