spring:
  application:
    name: EcommerceUsers
  datasource:
    driver-class-name: org.postgresql.Driver
    ulr: jdbc:postgresql://localhost:5432/ecommerceUsers
    username: postgres
    password: admin
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgresSQLDialect