spring:
  application:
    name: spring-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/acmicroserv_1?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: fran_18
    password: academia_ibm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080